name: react-native-android-build-apk
on:
  push:
    branches:
      - master
jobs:
  install-and-test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: create env
        env:
          IMGUR_CLIENT_ID: ${{ secrets.IMGUR_CLIENT_ID }}
          SNOO_USER_AGENT: ${{ secrets.SNOO_USER_AGENT }}
          SNOO_CLIENT_ID: ${{ secrets.SNOO_CLIENT_ID }}
          SNOO_CLIENT_SECRET: ${{ secrets.SNOO_CLIENT_SECRET }}
          SNOO_REFRESH_TOKEN: ${{ secrets.SNOO_REFRESH_TOKEN }}
        run: |
          printf "IMGUR_CLIENT_ID=$IMGUR_CLIENT_ID\nSNOO_USER_AGENT=$SNOO_USER_AGENT\nSNOO_CLIENT_ID=$SNOO_CLIENT_ID\nSNOO_CLIENT_SECRET=$SNOO_CLIENT_SECRET\nSNOO_REFRESH_TOKEN=$SNOO_REFRESH_TOKEN" >> .env && cat .env
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
  build-android:
    needs: install-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
      - name: Build Android Release
        run: |
          cd android && ./gradlew assembleRelease
      - name: Cleanup
        run: |
          cd .. && rm -rf .env
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-release.apk
          retention-days: 2
          path: android/app/build/outputs/apk/release/
